services:
  backend:
    build:
      context: .   # 👈 build from current backend folder
      dockerfile: Dockerfile
    volumes:
      - .:/app    # 👈 mount current folder into /app
    working_dir: /app
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: saas_db
      POSTGRES_USER: saas_user
      POSTGRES_PASSWORD: saas_pass
    ports:
      - "5432:5432"



  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data:
