# Generated by Django 5.2.6 on 2025-09-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blacklistedaccesstoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklistedaccesstoken',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='blacklistedaccesstoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blacklistedaccesstoken',
            name='jti',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='blacklistedaccesstoken',
            index=models.Index(fields=['jti'], name='blacklisted_jti_idx'),
        ),
    ]
